@host = http://localhost:3000
@Token = {{login.response.body.$.access_token}}

### 회원가입
POST {{host}}/user/register
Content-Type: application/json

{
    "email": "test@test.com",
    "password": "1234"
}

### 로그인(관리자)
# @name login
POST {{host}}/user/login
Content-Type: application/json

{
    "email": "test@test.com",
    "password": "1234"
}

### 로그인(비관리자)
# @name login
POST {{host}}/user/login
Content-Type: application/json

{
    "email": "test2@test.com",
    "password": "1234"
}

### 회원정보 가져오기
GET {{host}}/user/user-info
Authorization: Bearer {{Token}}
Content-Type: application/json

### 공연등록
POST {{host}}/performance
Authorization: Bearer {{Token}}
Content-Type: application/json

{
    "name": "테스트공연1",
    "description": "절거운 테스트공연1입니다",
    "dateTime": "2023-12-27 05:39:14",
    "location": "올림픽공원",
    "poster": "urllink",
    "category": "뮤지컬"
}

### 전체 공연보기
GET {{host}}/performance
Authorization: Bearer {{Token}}
Content-Type: application/json

### 전체 공연 검색하기
GET {{host}}/performance/search?name=테스&category=뮤
Authorization: Bearer {{Token}}
Content-Type: application/json

### 특정 공연보기
GET {{host}}/performance/id/2
Authorization: Bearer {{Token}}
Content-Type: application/json

### 특정 공연정보 수정
PUT {{host}}/performance/1
Authorization: Bearer {{Token}}
Content-Type: application/json

{
    "name": "테스트공연수정1",
    "description": "절거운 테스트공연수정1입니다",
    "dateTime": "2024-01-20 17:00:00",
    "location": "올림픽공원",
    "poster": "urllink",
    "category": "뮤지컬"
}

### 특정 공연정보 삭제
DELETE {{host}}/performance/1
Authorization: Bearer {{Token}}
Content-Type: application/json