@host = http://localhost:3000
@Token = {{login.response.body.$.access_token}}

// Users/Auth
### 회원가입
POST {{host}}/user/register
Content-Type: application/json

{
    "email": "test2@test.com",
    "password": "1234"
}

### 로그인(비관리자)
# @name login
POST {{host}}/user/login
Content-Type: application/json

{
    "email": "test@test.com",
    "password": "1234"
}

### 로그인(관리자)
# @name login
POST {{host}}/user/login
Content-Type: application/json

{
    "email": "test2@test.com",
    "password": "1234"
}

### 회원정보 가져오기
GET {{host}}/user/user-info
Authorization: Bearer {{Token}}
Content-Type: application/json


// Performances
### 공연등록
POST {{host}}/performance
Authorization: Bearer {{Token}}
Content-Type: application/json

{
    "name": "테스트공연2",
    "description": "절거운 테스트공연1입니다",
    "dateTime": "2023-01-05 17:00:00",
    "location": "올림픽공원",
    "poster": "urllink",
    "category": "연극"
}

### 전체 공연보기
GET {{host}}/performance
Authorization: Bearer {{Token}}
Content-Type: application/json

### 전체 공연 검색하기
GET {{host}}/performance/search?name=테스&category=뮤
Authorization: Bearer {{Token}}
Content-Type: application/json

### 특정 공연보기
GET {{host}}/performance/id/1
Authorization: Bearer {{Token}}
Content-Type: application/json

### 특정 공연정보 수정
PUT {{host}}/performance/1
Authorization: Bearer {{Token}}
Content-Type: application/json

{
    "name": "테스트공연수정1",
    "description": "절거운 테스트공연수정1입니다",
    "dateTime": "2024-01-20 16:00:00",
    "location": "올림픽공원",
    "poster": "urllink",
    "category": "뮤지컬"
}

### 특정 공연정보 삭제
DELETE {{host}}/performance/1
Authorization: Bearer {{Token}}
Content-Type: application/json

// Seats
### 좌석등록
POST {{host}}/performance/1/seat
Authorization: Bearer {{Token}}
Content-Type: application/json

{
    "name": "B4",
    "price": 30000
}

### 좌석등록
POST {{host}}/performance/1/seat/csv
Authorization: Bearer {{Token}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="musical.csv"
Content-Type: text/csv

< ./ect/musical.csv
------WebKitFormBoundary7MA4YWxkTrZu0gW--



### 특정 좌석보기
GET {{host}}/performance/1/seat/1
Authorization: Bearer {{Token}}
Content-Type: application/json

### 좌석정보 수정
PUT {{host}}/performance/2/seat/2
Authorization: Bearer {{Token}}
Content-Type: application/json

{
    "name": "A1",
    "price": 50000,
    "state": "ForSale"
}

### 좌석정보 삭제
DELETE {{host}}/performance/2/seat/1
Authorization: Bearer {{Token}}
Content-Type: application/json


// 예약
### 예약등록
POST {{host}}/reservation
Authorization: Bearer {{Token}}
Content-Type: application/json

[
  {
    "seat_id": 1,
    "reservation_name": "홍길동",
    "payment_amount": 50000
  },
    {
      "seat_id": 2,
      "reservation_name": "김철수",
      "payment_amount": 50000
    }
]

### 예약보기
GET {{host}}/reservation
Authorization: Bearer {{Token}}
Content-Type: application/json

### 특정 예약 보기
GET {{host}}/reservation/8
Authorization: Bearer {{Token}}
Content-Type: application/json

### 특정 예약 취소
DELETE {{host}}/reservation/8
Authorization: Bearer {{Token}}
Content-Type: application/json